export const PATIENTS = [
  {
    id: 1, status: 'yet_to_be_seen', name: 'Jane Testpatient',
    provider: 'Dr Adam Bricks', apptInfo: 'Cardiology',
    time: '06:00 AM', vaccine: false, copay: 25.0, due: 0.0,
    adhoc: false, payment: 'pending', refer: false,
    survey: false, product: false, scheduling: 'intake',
  },
  {
    id: 2, status: 'yet_to_be_seen', name: 'Saif K&Yu',
    provider: 'Dr Adam Bricks', apptInfo: 'Pediatric',
    time: '06:00 AM', vaccine: true, copay: 30.0, due: 15.0,
    adhoc: false, payment: 'paid', refer: true,
    survey: false, product: false, scheduling: 'intake',
  },
  {
    id: 3, status: 'yet_to_be_seen', name: 'Test Test',
    provider: 'Dr Adam Bricks', apptInfo: 'Pediatric',
    time: '06:45 AM', vaccine: false, copay: 20.0, due: 0.0,
    adhoc: true, payment: 'pending', refer: false,
    survey: true, product: false, scheduling: 'intake',
  },
  {
    id: 4, status: 'yet_to_be_seen', name: 'Laura Cummings',
    provider: 'Dr Adam Bricks', apptInfo: 'Cardiology',
    time: '07:15 AM', vaccine: false, copay: 25.0, due: 5.0,
    adhoc: false, payment: 'pending', refer: false,
    survey: false, product: true, scheduling: 'intake',
  },
  {
    id: 5, status: 'yet_to_be_seen', name: 'Santenc Testpatient',
    provider: 'Dr Adam Bricks', apptInfo: 'Cardiology',
    time: '01:15 PM', vaccine: false, copay: 35.0, due: 0.0,
    adhoc: false, payment: 'paid', refer: false,
    survey: true, product: false, scheduling: 'intake',
  },
  {
    id: 6, status: 'yet_to_be_seen', name: 'Kelm Testpatient',
    provider: 'Dr Adam Bricks', apptInfo: 'Primary Care',
    time: '01:30 PM', vaccine: false, copay: 60.0, due: 0.0,
    adhoc: false, payment: 'pending', refer: false,
    survey: false, product: false, scheduling: 'intake',
  },
  {
    id: 7, status: 'checked_in', name: 'Maria Lopez',
    provider: 'Dr Adam Bricks', apptInfo: 'Cardiology',
    time: '08:00 AM', vaccine: false, copay: 40.0, due: 0.0,
    adhoc: false, payment: 'paid', refer: false,
    survey: false, product: false, scheduling: 'done',
  },
  {
    id: 8, status: 'checked_in', name: 'John Smith',
    provider: 'Dr Adam Bricks', apptInfo: 'Primary Care',
    time: '09:30 AM', vaccine: true, copay: 50.0, due: 10.0,
    adhoc: false, payment: 'pending', refer: true,
    survey: false, product: false, scheduling: 'done',
  },
  {
    id: 9, status: 'cancelled', name: 'Bob Davis',
    provider: 'Dr Adam Bricks', apptInfo: 'Pediatric',
    time: '10:00 AM', vaccine: false, copay: 0.0, due: 0.0,
    adhoc: false, payment: 'n/a', refer: false,
    survey: false, product: false, scheduling: 'cancelled',
  },
];
